name: Daily Gold Price Update

on:
  schedule:
    - cron: '0 0 * * *' # প্রতিদিন রাত ১২টায় অটো চলবে
  workflow_dispatch: # চাইলে আপনি নিজেও বাটন চেপে রান করতে পারবেন

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests feedparser

      - name: Run Script
        env:
          GOLD_API_KEY: ${{ secrets.GOLD_API_KEY }}
        run: python update_gold.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add index.md
          git commit -m "Daily Gold Price and News Update"
          git push
